### ISSUE TITLE
1.0 API deprecation killed Kwitty?

### ISSUE THREAD

**Issue by mindplay-dk** [killwing/kwitty#1]
Looks like the deprecation of the 1.0 API in favor of the 1.1 API killed off Kwitty?

I can still log in and view my timelines - but I can no longer post.

The error message on screen reads: "Failed to update status: could not authenticate you."

```
Tweet.update() kt.js:487
Request.send(): https://api.twitter.com/1.1/statuses/update.json 
Object
 kt.js:139
OAuth Signed Request kt.js:112
Failed to load resource: the server responded with a status of 401 (Unauthorized) https://api.twitter.com/1.1/statuses/update.json
API.sendRequest() - error kt.js:192
errorHandler(): Failed to update status 
Object
 base.js:1860
```

**Comment by killwing** [comment]
All kwitty's APIs have been upgraded to v1.1.
Did you fail to tweet with these special chars `! ' ( ) *` or any tweets?

**Comment by mindplay-dk** [comment]
Guess there must have been a special character in there somewhere - a simple "hello world" went through fine.

Why would that cause problems? I don't think I was using any characters I don't normally use.

**Comment by killwing** [comment]
It may be the Twitter API problem since v1.1.
Check this: http://stackoverflow.com/questions/14672502/bug-or-spec-change-of-twitter-api-1-1
I'll apply the workaround in next version.

**Comment by mindplay-dk** [comment]
The following message seems to reproduce the issue:

`@friend blah! blah blah ;-)`
